# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apx < Formula
  desc "API Publishing eXperience CLI"
  homepage "https://github.com/infobloxopen/apx"
  version "0.1.0-alpha.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/infobloxopen/apx/releases/download/v0.1.0-alpha.1/apx_0.1.0-alpha.1_darwin_amd64.tar.gz"
      sha256 "e9c64a02d59eea09ed8a636dfbe4e98269064c4189061c5f5a1b1a663bcf3795"

      define_method(:install) do
        bin.install "apx"
        (bash_completion/"apx").write `#{bin}/apx completion bash`
        (fish_completion/"apx.fish").write `#{bin}/apx completion fish`
        (zsh_completion/"_apx").write `#{bin}/apx completion zsh`
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/infobloxopen/apx/releases/download/v0.1.0-alpha.1/apx_0.1.0-alpha.1_darwin_arm64.tar.gz"
      sha256 "9e6161e57c921c17e8a4fa7c6b1d0cf4cc8d41290e9154b89c843bcd50fe9127"

      define_method(:install) do
        bin.install "apx"
        (bash_completion/"apx").write `#{bin}/apx completion bash`
        (fish_completion/"apx.fish").write `#{bin}/apx completion fish`
        (zsh_completion/"_apx").write `#{bin}/apx completion zsh`
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/infobloxopen/apx/releases/download/v0.1.0-alpha.1/apx_0.1.0-alpha.1_linux_amd64.tar.gz"
      sha256 "a55de3b5a3d1f4f51ff5927e71468d6e0d127e47042e52922e0a8e83c5044a95"
      define_method(:install) do
        bin.install "apx"
        (bash_completion/"apx").write `#{bin}/apx completion bash`
        (fish_completion/"apx.fish").write `#{bin}/apx completion fish`
        (zsh_completion/"_apx").write `#{bin}/apx completion zsh`
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/infobloxopen/apx/releases/download/v0.1.0-alpha.1/apx_0.1.0-alpha.1_linux_arm64.tar.gz"
      sha256 "f5ece8072a128bc1f6c552fe5a0d72b3c54e0f9aabb8082ef232e7d4f0fdbbd0"
      define_method(:install) do
        bin.install "apx"
        (bash_completion/"apx").write `#{bin}/apx completion bash`
        (fish_completion/"apx.fish").write `#{bin}/apx completion fish`
        (zsh_completion/"_apx").write `#{bin}/apx completion zsh`
      end
    end
  end

  test do
    system "#{bin}/apx", "--version"
  end
end
