# This file was generated by GoReleaser. DO NOT EDIT.
cask "apx" do
  version "0.20.1"

  on_macos do
    on_intel do
      sha256 "6a9a721265e9ee3f1cd5b2dbdabe54e0f653e5275f9f695972dd5ef92daeb9ac"
      url "https://github.com/infobloxopen/apx/releases/download/v#{version}/apx_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "62fc3e1d2d7afc14624e16b8bda604956022bdeb6feed1be6fcec0c8944d6d38"
      url "https://github.com/infobloxopen/apx/releases/download/v#{version}/apx_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "989df7a6e232af64bcb767d84e1bbe98ca29c411f8825ce6da5de31c65772150"
      url "https://github.com/infobloxopen/apx/releases/download/v#{version}/apx_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4e979bda9a4cf31364681793b93b6b9a85464458b50fc82270a47b7a22ed8211"
      url "https://github.com/infobloxopen/apx/releases/download/v#{version}/apx_#{version}_linux_arm64.tar.gz"
    end
  end

  name "apx"
  desc "API Publishing eXperience CLI"
  homepage "https://github.com/infobloxopen/apx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apx"
  bash_completion "completions/apx.bash"
  fish_completion "completions/apx.fish"
  zsh_completion "completions/apx.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/apx"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The binary is not signed by Apple. On first run macOS may show a
    security warning. The post-install hook attempts to clear the
    quarantine flag automatically. If you still see the warning, run:
      xattr -dr com.apple.quarantine $(brew --caskroom)/apx
  EOS
end
