# This file was generated by GoReleaser. DO NOT EDIT.
cask "apx" do
  name "apx"
  desc "API Publishing eXperience CLI"
  homepage "https://github.com/infobloxopen/apx"
  version "0.8.0-beta.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apx"
  bash_completion "completions/apx.bash"
  zsh_completion "completions/apx.zsh"
  fish_completion "completions/apx.fish"

  on_macos do
    on_intel do
      url "https://github.com/infobloxopen/apx/releases/download/v#{version}/apx_#{version}_darwin_amd64.tar.gz"
      sha256 "0c468a1378ca08d502d38ba0dc07aed760bb7e2b791c06a85fc48ca16186fbfb"
    end
    on_arm do
      url "https://github.com/infobloxopen/apx/releases/download/v#{version}/apx_#{version}_darwin_arm64.tar.gz"
      sha256 "2c34e610a1b92977f74ec752c1f3772c0e1b1ca90d6a678a17fad810ad864c03"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/infobloxopen/apx/releases/download/v#{version}/apx_#{version}_linux_amd64.tar.gz"
      sha256 "9b743a35b2d7d1469ed6edc8e81a77278ac3fd6bcc02ce4063c7c2653d54dec7"
    end
    on_arm do
      url "https://github.com/infobloxopen/apx/releases/download/v#{version}/apx_#{version}_linux_arm64.tar.gz"
      sha256 "c6cf0abe7e21f28d6ed3855d976943dc298bfa5b6a5d950b95e972f3a8caca75"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/apx"]
    end
  end

  caveats do
    "The binary is not signed by Apple. On first run macOS may show a"
    "security warning. The post-install hook attempts to clear the"
    "quarantine flag automatically. If you still see the warning, run:"
    "  xattr -dr com.apple.quarantine $(brew --caskroom)/apx"
  end

  # No zap stanza required
end
