# This file was generated by GoReleaser. DO NOT EDIT.
cask "apx" do
  version "0.21.0"

  on_macos do
    on_intel do
      sha256 "242a35caf65c39ea70f959871e4ed2c36b073f030c2fcb4a5af764050565ae56"
      url "https://github.com/infobloxopen/apx/releases/download/v#{version}/apx_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "69114d08a5e8b0451f8ed57fcfc424b487f780f2cc4153981340f9e27b1c7ad8"
      url "https://github.com/infobloxopen/apx/releases/download/v#{version}/apx_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2a30a48d2e4aaeb3821ad07f981ea9ccf10a5e037b0d53d252421fe717b7303c"
      url "https://github.com/infobloxopen/apx/releases/download/v#{version}/apx_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e1df5eb5937a6eb31e984f649be88ab47d9989ec2d17bf04ee0c8c0e4456a2c9"
      url "https://github.com/infobloxopen/apx/releases/download/v#{version}/apx_#{version}_linux_arm64.tar.gz"
    end
  end

  name "apx"
  desc "API Publishing eXperience CLI"
  homepage "https://github.com/infobloxopen/apx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apx"
  bash_completion "completions/apx.bash"
  fish_completion "completions/apx.fish"
  zsh_completion "completions/apx.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/apx"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The binary is not signed by Apple. On first run macOS may show a
    security warning. The post-install hook attempts to clear the
    quarantine flag automatically. If you still see the warning, run:
      xattr -dr com.apple.quarantine $(brew --caskroom)/apx
  EOS
end
