# This file was generated by GoReleaser. DO NOT EDIT.
cask "devedge" do
  version "0.14.1"

  on_macos do
    on_intel do
      sha256 "b1444e48ea5b7cad0d1fd7957f398258eef340d0d221d5d3444382c07cf68cb6"
      url "https://github.com/infobloxopen/devedge/releases/download/v#{version}/devedge_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "827c69338940e38578e86f018cbcfa9aa052060f830c4348285fd1c6415b54b6"
      url "https://github.com/infobloxopen/devedge/releases/download/v#{version}/devedge_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dfce73a18b6382ab71a975f86799632000fd2aebeef1e9e400a7a1b24e566987"
      url "https://github.com/infobloxopen/devedge/releases/download/v#{version}/devedge_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d0e18914b349ecdb55095c8e24bb6865d7226181a61b4ad3c233284511aa4bf7"
      url "https://github.com/infobloxopen/devedge/releases/download/v#{version}/devedge_#{version}_linux_arm64.tar.gz"
    end
  end

  name "devedge"
  desc "Local development edge router and name registry"
  homepage "https://github.com/infobloxopen/devedge"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "de"
  binary "devedged"
  binary "devedge-dns-webhook"

  postflight do
    if OS.mac?
      %w[de devedged devedge-dns-webhook].each do |bin|
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/#{bin}"]
      end
    end
  end

  # No zap stanza required

  caveats <<~EOS
    To get started:
      de install    # set up daemon, mkcert CA, DNS
      de start      # start the background daemon
      de doctor     # verify everything is healthy

    The binaries are not signed by Apple. The post-install hook clears
    the quarantine flag automatically. If macOS still blocks them, run:
      xattr -dr com.apple.quarantine $(brew --caskroom)/devedge
  EOS
end
