# This file was generated by GoReleaser. DO NOT EDIT.
cask "devedge" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "f94dfccbf70f946dcd2eafb9d186b55ca7ee1e26ed0476dd8c71ca39b55b5214"
      url "https://github.com/infobloxopen/devedge/releases/download/v#{version}/devedge_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1c2ffc84eb751b793cf6d30d7c043daedc4844323a1a01bc8c2782e0b334bfda"
      url "https://github.com/infobloxopen/devedge/releases/download/v#{version}/devedge_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0f00613e0e21ef0e7efa1f3e4cd688a14c4d15433fa7edf03ffdb70476c50d4f"
      url "https://github.com/infobloxopen/devedge/releases/download/v#{version}/devedge_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5d6ee23fc56bf47349985afa8f8b5300a7c8a57b289f8f5fa8fc057ab1951621"
      url "https://github.com/infobloxopen/devedge/releases/download/v#{version}/devedge_#{version}_linux_arm64.tar.gz"
    end
  end

  name "devedge"
  desc "Local development edge router and name registry"
  homepage "https://github.com/infobloxopen/devedge"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "de"
  binary "devedged"
  binary "devedge-dns-webhook"

  postflight do
    if OS.mac?
      %w[de devedged devedge-dns-webhook].each do |bin|
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/#{bin}"]
      end
    end
  end

  # No zap stanza required

  caveats <<~EOS
    To get started:
      de install    # set up daemon, mkcert CA, DNS
      de start      # start the background daemon
      de doctor     # verify everything is healthy

    The binaries are not signed by Apple. The post-install hook clears
    the quarantine flag automatically. If macOS still blocks them, run:
      xattr -dr com.apple.quarantine $(brew --caskroom)/devedge
  EOS
end
