# This file was generated by GoReleaser. DO NOT EDIT.
cask "devedge" do
  version "0.16.0"

  on_macos do
    on_intel do
      sha256 "e91f1bd733e8f405bb4c61c1814e7f1429dc361a03c44e8aa87f385de3851f34"
      url "https://github.com/infobloxopen/devedge/releases/download/v#{version}/devedge_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "15ef9c8923c6c8e2dbdcd757226749b093350c3a845acd2f339943dcc137d9a6"
      url "https://github.com/infobloxopen/devedge/releases/download/v#{version}/devedge_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f344d747b3cfb7f3a2dcc0257a45b1eec3d40ef6363629040b60107f78afbd3e"
      url "https://github.com/infobloxopen/devedge/releases/download/v#{version}/devedge_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c9069ccaa1e2ff12dfff12684f801aa3f3042783619defc5bece32c5880157df"
      url "https://github.com/infobloxopen/devedge/releases/download/v#{version}/devedge_#{version}_linux_arm64.tar.gz"
    end
  end

  name "devedge"
  desc "Local development edge router and name registry"
  homepage "https://github.com/infobloxopen/devedge"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "de"
  binary "devedged"
  binary "devedge-dns-webhook"

  postflight do
    if OS.mac?
      %w[de devedged devedge-dns-webhook].each do |bin|
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/#{bin}"]
      end
    end
  end

  # No zap stanza required

  caveats <<~EOS
    To get started:
      de install    # set up daemon, mkcert CA, DNS
      de start      # start the background daemon
      de doctor     # verify everything is healthy

    The binaries are not signed by Apple. The post-install hook clears
    the quarantine flag automatically. If macOS still blocks them, run:
      xattr -dr com.apple.quarantine $(brew --caskroom)/devedge
  EOS
end
